name: bauh # you probably want to 'snapcraft register <name>'
base: core18
version: '0.6.1' 
summary: Manage your Flatpaks, Snaps and AUR packages.
description: |
  bauh ( ba-oo ) is a graphical user interface to manage your Linux applications ( packages ). 
  It currently supports Flatpak, Snap and AUR packaging types. 
  When you launch bauh you will see a management panel where you can search, update, install, uninstall 
  and launch applications. You can also downgrade some applications depending on the package technology.
# icon: desktop/htmldoc-128.png
grade: stable 
confinement: strict

apps:
  bauh:
    command: desktop-launch $SNAP/bin/bauh
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - opengl

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
  bauh:
    after: [desktop-qt5]
    plugin: python
    source: https://github.com/vinifmor/bauh.git
    source-tag: 0.6.1
    build-packages:
      - python3
    stage-packages:
      - python3
      - libc-bin
      - locales
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libavahi-client3
      - libavahi-common3
      - libcairo-gobject2
      - libcups2
      - libepoxy0
      - libgtk-3-0
      - libwayland-cursor0
      - libwayland-egl1
      - libxcomposite1
      - libxcursor1
      - libxinerama1
      - libxrandr2

